import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useContext } from "react";
import CommissionsSection from "../components/CommissionsSection";
import ContactSection from "../components/ContactSection";
import Footer from "../components/Footer";
import Header from "../components/Header";
import LandingSection from "../components/LandingSection";
import ShowcaseSection from "../components/ShowcaseSection";
import { ThemeContext, useTheme } from "../context/ThemeContext";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Reid Cole - Web Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />

        <LandingSection />

        <ShowcaseSection />
        {/* <CommissionsSection /> */}

        <ContactSection />

        <Footer />
      </main>
    </>
  );
};

export default Home;
